<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Assetwig\View\TwigResolver'                  => __DIR__ . '/View/TwigResolver.php',
    'Assetwig\View\TwigRenderer'                  => __DIR__ . '/View/TwigRenderer.php',
    'Assetwig\View\TwigStrategy'                  => __DIR__ . '/View/TwigStrategy.php',
    'Assetwig\Assetic\Assetic'                    => __DIR__ . '/Assetic/Assetic.php',
    'Assetwig\Assetic\AssetWriter'                => __DIR__ . '/Assetic/AssetWriter.php',
    'Assetwig\Twig\Extension'                     => __DIR__ . '/Twig/Extension.php',
    'Assetwig\Twig\Environment'                   => __DIR__ . '/Twig/Environment.php',
    'Assetwig\Twig\Extension\Render\TokenParser'  => __DIR__ . '/Twig/Extension/Render/TokenParser.php',
    'Assetwig\Twig\Extension\Render\RenderNode'   => __DIR__ . '/Twig/Extension/Render/RenderNode.php',
    'Assetwig\Twig\HelperFunction'                => __DIR__ . '/Twig/HelperFunction.php',
    'Assetwig\Module'                             => __DIR__ . '/Module.php',
    'Assetwig\ExceptionInterface'                 => __DIR__ . '/ExceptionInterface.php',
    'Assetwig\Exception\InvalidArgumentException' => __DIR__ . '/Exception/InvalidArgumentException.php',
    'Assetwig\Exception\RuntimeException'         => __DIR__ . '/Exception/RuntimeException.php',
    'Assetwig\Exception\DomainException'          => __DIR__ . '/Exception/DomainException.php',
);